### ISSUE TITLE
npm authToken not working after 1 hour

### ISSUE THREAD

**Issue by B-Souty** [kuoruan/verdaccio-openid#2]
I'm using this plugin to login to verdaccio using Google oauth.

I then click on the gear icon in verdaccio to retrieve the authToken. 

Using this token I can then publish and consume packges in my allowed scope. However, after 1 hour the authToken doesn't work and I need to login to verdaccio again to retrieve a token.

I thought this was due to the default verdaccio Web UI session lifetime (1h) but after changing that, I noticed the authToken still expires after 1 hour.

Any idea where this 1h expiration might be coming from?

**Comment by B-Souty** [comment]
I found that the expiration is set on the jwt token and can be increased by the `security.api.jwt.sign.expiresIn` setting. I feel like setting a long expiration time is counter productive though. Isn't there a way to keep a short expiration time and let the plugin refresh the jwt token when needed?

**Comment by kuoruan** [comment]
Hi @B-Souty, we do not have a API to refresh the token (no refresh token generated)
I'm finding a way to keep the user login.
