### ISSUE TITLE
Absolute urls ignore url_prefix config

### ISSUE THREAD

**Issue by simone-gasparini** [kuoruan/verdaccio-openid#3]
When Verdaccio works under a path with `url_prefix` set for example to `/verdaccio`, the absolutes url under constant are not mapped correctly.

In config.yaml:
`url_prefix: /verdaccio`

In [PatchHtml.ts#L24](https://github.com/kuoruan/verdaccio-openid/blob/main/src/server/plugin/PatchHtml.ts#L24) the `staticPath` is configured in [constants.ts#L5](https://github.com/kuoruan/verdaccio-openid/blob/main/src/server/constants.ts#L5) and does not consider the `url_prefix` configuration, this make the plugin unusable.

**Comment by kuoruan** [comment]
@simone-gasparini Thank you for the report. I'm fixing it.
